# Generated by Django 5.2.14 on 2026-05-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='device',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='run',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='run',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='seed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(default='running', max_length=20),
        ),
    ]
